### 1. 새로운 생일 펀딩방 개설하기
POST http://localhost:8080/api/funding
Content-Type: application/json

{
  "title": "소진이의 생일 펀딩! 닌텐도 스위치 OLED 🎮",
  "targetAmount": 150000,
  "accountInfo": "전북은행 1021013812052"
}

> {%
    // 방금 생성된 펀딩방의 ID를 변수에 저장해 둡니다.
    client.global.set("roomId", response.body.id);
%}

###

### 2. [친구용] 특정 펀딩방 정보 조회하기 (달성률 및 계좌 확인)
GET http://localhost:8080/api/funding/{{roomId}}

###

### 3. [친구 1: 민석] 펀딩 참여 신청하기 (30,000원)
POST http://localhost:8080/api/funding/{{roomId}}/apply
Content-Type: application/json

{
  "contributorName": "민석",
  "amount": 30000,
  "message": "생일 축하한다 소진아! 스위치 사서 레전드 아르세우스 하자 🕹️"
}

###

### 4. [친구 2: 동구] 펀딩 참여 신청하기 (50,000원)
POST http://localhost:8080/api/funding/{{roomId}}/apply
Content-Type: application/json

{
  "contributorName": "동구",
  "amount": 50000,
  "message": "휴학 축하하고 생일도 축하해! 맛있는 거 사먹어라~"
}

###

### 5. 👑 [방장 전용] 친구들의 신청 내역 & 메시지 목록 조회
GET http://localhost:8080/api/funding/{{roomId}}/admin/contributions

###

### 6. 👑 [방장 전용] 민석이의 입금 확인 후 승인 처리 (contributionId = 1)
POST http://localhost:8080/api/funding/contributions/1/approve

###

### 7. 👑 승인 후 펀딩방 다시 조회해보기 (currentAmount가 30,000원으로 올랐는지 확인!)
GET http://localhost:8080/api/funding/{{roomId}}


### 8. 👑 [방장 전용] 동구의 입금도 확인 후 승인 처리 (contributionId = 2)
POST http://localhost:8080/api/funding/contributions/2/approve

###

### 9. 승인 후 펀딩방 다시 조회해보기 (이제 80,000원이 되었는지 확인!)
GET http://localhost:8080/api/funding/{{roomId}}